Posts support
pixeltree/MyFirstBlog pull request #4
Opened 2022-11-24 19:46 UTC by MaxHalleran

Added support for posts from the server. Blog posts will now be generated directly from the server. I removed the articles from the template and replaced them with the blog posts.

2022-11-25 20:27 UTC, Nolan-E requested changes
Few comments

2022-11-25 20:27 UTC, Nolan-E commented on src/api/postsApi.js
> +    return []
Does this actually return an array on success? We're fetching a single post.

2022-11-25 22:11 UTC, MaxHalleran commented on src/api/axiosConfig.js
> +const BASE_URL = process.env.SERVER_URL
Nope, but since it's pointing at a dotnet server I've updated it to "DOTNET_SERVER_URL".

2022-11-25 22:11 UTC, MaxHalleran commented on src/api/posts.js
> +export default postsApi
Changed

2022-11-28 05:14 UTC, MaxHalleran commented on src/api/axiosConfig.js
> +}
Moved to `@/lib/isHyperlink.js`. I'm not 100% on the file name.

2022-11-28 05:19 UTC, MaxHalleran commented on src/components/Header.jsx
> -
Refactoring the theme is out of scope for this PR. 

I'm trying to do some drive by slimming/refactoring of these files when features interact with them.

2022-11-28 05:22 UTC, MaxHalleran commented on src/lib/generateRssFeed.js
>    let author = {
Updated!

2022-11-28 05:30 UTC, MaxHalleran commented on src/lib/generateRssFeed.js
> +  for (let post of posts) {
Refactored to use a forEach loop

2022-11-28 05:34 UTC, MaxHalleran commented on src/api/postsApi.js
> +    return []
It returns an object. Changed!

2022-11-28 06:09 UTC, MaxHalleran commented on src/components/Header.jsx
> -
https://github.com/pixeltree/MyFirstBlog/pull/5

Started a refactor here.

2022-11-28 16:28 UTC, Nolan-E approved these changes
🌮

2022-11-28 18:26 UTC, merged